name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Run test script
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
          command: npm run test
          install-command: npm ci
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_ID: ${{ secrets.TEST_ID }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          REACT_APP_SERVER_URL: ${{ secrets.SERVER_URL }}
          REACT_APP_PLATFORM_URL: http://localhost:3002/
